spring.application.name=share2teach
spring.datasource.url=jdbc:postgresql://localhost:5432/share2teach_db
spring.datasource.username=postgres
spring.datasource.password=kenewang
spring.datasource.driver-class-name=org.postgresql.Driver

# Don’t let Hibernate try to change your existing tables
spring.jpa.hibernate.ddl-auto=none

# Optional, but helpful for debugging SQL queries
spring.jpa.show-sql=true
server.port=8081

